server:
  port: 1000
#  使用在服务代理器之后
#  use-forward-headers: true
spring:
  application:
    name: admin
  boot:
    admin:
      ui:
        title: SpringBootAdmin-Server
      notify:
        mail:
          from: ${spring.mail.username}
          to: 2377881365@qq.com
      routes:
        #        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,activiti,hystrix.stream,turbine.stream
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,activiti,hystrix.stream
  #      turbine:
  #        clusters: default
  #        location: microservice-hystrix-turbine
  security:
    user:
      name: admin #配置登录的账号
      password: password #配置登录的密码
  mail:
    host: smtp.qq.com
    username: 654600784@qq.com
    password: ryuwsxunlaxvbcbg
    properties:
      mail:
        smtp:
          auth: true
#Actuator配置：暴露敏感路径，默认情况下，敏感路径并不暴露
management:
  endpoints:
    web:
      exposure:
        # 暴露xxx端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
        include: "*"
        # 不暴露哪些端点
        exclude: env,beans,configprops
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: ALWAYS
  health:
    redis:
      enabled: false

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      #      startup: ${random.int}  #needed to trigger info and endpoint update after restart
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
    #    # 是否注册IP到eureka server，如不指定或设为false，那就回注册主机名到eureka server
    prefer-ip-address: true
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      #      defaultZone: http://admin:admin@peer1:8761/eureka/,http://admin:admin@peer2:8762/eureka/
      defaultZone: http://admin:admin@peer1:8761/eureka/
    registry-fetch-interval-seconds: 5
logging:
  file: /home/admin/log/admin.log
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'