server:
  port: 2000
spring:
  application:
    name: histrixmonitor
#服务端点暴露
management:
  endpoints:
    web:
      exposure:
        # 暴露xxx端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
        include: auditevents,caches,conditions,flyway,health,heapdump,httptrace,info,integrationgraph,jolokia,logfile,loggers,liquibase,metrics,mappings,prometheus,scheduledtasks,sessions,shutdown,threaddump,hystrix.stream
        # 不暴露哪些端点
        exclude: env,beans,configprops
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
  health:
    redis:
      enabled: false
#eureka注册
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://admin:admin@peer1:8761/eureka/,http://admin:admin@peer2:8762/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就回注册主机名到eureka server
    prefer-ip-address: true
turbine:
  # 要监控的微服务列表，多个用,分割
  app-config: ht
  cluster-name-expression: "'default'"